### ISSUE TITLE
Asymmetrical Version?

### ISSUE THREAD

**Issue by chase-miller** [StarWhiz/NanoPi-R6S-CPU-Optimization-for-Gigabit-SQM#2]
Thank you for sharing! 

Why is there a different version for asymmetrical connections? My very rudimentary understanding of this is that we’re essentially instructing something (cake/sqm/some other service) to use the faster cores. What role does the symmetry of the up/downlink have to do with this?

A related question: we would still specify the link speed (via the GUI) for sqm after making these modifications, right?

Thanks again!

**Comment by chase-miller** [comment]
I just noticed https://forum.openwrt.org/t/nanopi-r6s-with-openwrt/167611/91. Is the idea to give more horsepower (faster cores) to the downlink and less to the uplink?

> Now I think to optimize for my assymetrical connection I should focus the big cores on ingress queues and put slow cores on all egress queues.

**Comment by StarWhiz** [comment]
Hi chase, I'm not that very smart. I just played around with the affinities and queues and found it worked best for my assymetrical connection. I can't really explain why :(

I think multi-core design is in the works in the SQM space https://docs.google.com/document/d/1HxIU_TEBI6xG9jRHlr8rzyyxFEN43zMcJXUFlRuhiUI/edit?pli=1

**Comment by StarWhiz** [comment]
Hi @chase-miller , I'm not that very smart. I just played around with the affinities and queues and found it worked best for my assymetrical connection.

But to answer your question, Yes. As you said in the second comment that was what I was thinking, to give more horsepower to downlink and less to the uplink.

As for your other question, yes you would still specify the link speed (via the GUI) for sqm after making these modifications.

I think multi-core design is in the works in the SQM space https://docs.google.com/document/d/1HxIU_TEBI6xG9jRHlr8rzyyxFEN43zMcJXUFlRuhiUI/edit?pli=1

But since that isn't available playing around with the affinity and queues is all I can do.
